version: "3"

services:

  redis:
    image: redis

  postgres:
    image: eeacms/postgres:9.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DBNAME: "sentry"
      POSTGRES_DBUSER: "sentry"
      POSTGRES_DBPASS: "sentry"
    volumes:
       - ./data/postgres:/var/lib/postgresql/data

  sentry:
    image: sentry:latest
    volumes:
      - ./data/sentry:/data
    depends_on:
       - redis
       - postgres
    ports:
      - 8080:9000
    environment:
      SENTRY_SECRET_KEY: "verysecret"
      SENTRY_POSTGRES_HOST: "postgres"
      SENTRY_DB_USER: "postgres"
      SENTRY_DB_PASSWORD: "postgres"
      SENTRY_REDIS_HOST: "redis"
      C_FORCE_ROOT: "true"
    command: "sentry run web"

  sentry_celery_beat:
    image: sentry:latest
    depends_on:
     - redis
     - postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: "verysecret"
      SENTRY_POSTGRES_HOST: "postgres"
      SENTRY_DB_USER: "postgres"
      SENTRY_DB_PASSWORD: "postgres"
      SENTRY_REDIS_HOST: "redis"
      C_FORCE_ROOT: "true"

  sentry_celery_worker:
    image: sentry:latest
    depends_on:
     - redis
     - postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: "verysecret"
      SENTRY_POSTGRES_HOST: "postgres"
      SENTRY_DB_USER: "postgres"
      SENTRY_DB_PASSWORD: "postgres"
      SENTRY_REDIS_HOST: "redis"
      C_FORCE_ROOT: "true"

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    environment:
      docker: "true"
      production: "false"
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs
    ports:
      - 9000:9000
      - 9501:9501

  web:
    build:
      context: .
      dockerfile: web.dockerfile
    volumes:
      - ./config:/etc/nginx/conf.d
    depends_on:
      - sentry
      - api
    ports:
      - 80:80
      - 443:443

  mysql-db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
     - ./data/mysql:/var/lib/mysql
    ports:
      - 3307:3306