version: "3"

services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    environment:
      docker: "true"
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs
    ports:
      - 9000:9000
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - 8080:80
  mysql-db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
     - ./data:/var/lib/mysql
    ports:
      - 3307:3306