version: "3"

services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs
    ports:
      - 9000:9000
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - 8080:80
#  db:
#    image: