version: "3"

services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    environment:
      docker: "true"
      production: "false"
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs
    ports:
      - 9000:9000
      - 9501:9501

  web:
    build:
      context: .
      dockerfile: web.dockerfile
    volumes:
      - ./config:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443

  mysql-db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
     - ./data:/var/lib/mysql
    ports:
      - 3307:3306